"""location and weather

Revision ID: 46d29aa5c513
Revises: fbd5c91275da
Create Date: 2025-05-25 09:52:17.491172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision: str = "46d29aa5c513"
down_revision: Union[str, None] = "fbd5c91275da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "heading",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default=sa.text("'0.0'"),  # <-- DODANE server_default
        ),
    )
    op.alter_column(
        "locations",
        "position",
        existing_type=ga.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        nullable=False,
    )
    op.alter_column(
        "route_points",
        "planned_position",
        existing_type=ga.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        nullable=False,
    )
    op.alter_column(
        "route_points", "status", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.add_column(
        "weather_data", sa.Column("location_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        "idx_weather_data_location_id", "weather_data", ["location_id"], unique=False
    )
    op.create_foreign_key(
        None, "weather_data", "locations", ["location_id"], ["location_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "weather_data", type_="foreignkey")
    op.drop_index("idx_weather_data_location_id", table_name="weather_data")
    op.drop_column("weather_data", "location_id")
    op.alter_column(
        "route_points", "status", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "route_points",
        "planned_position",
        existing_type=ga.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        nullable=True,
    )
    op.alter_column(
        "locations",
        "position",
        existing_type=ga.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        nullable=True,
    )
    op.drop_column("locations", "heading")
    # ### end Alembic commands ###
