"""boats

Revision ID: 56a9446527bb
Revises: 6829279ab8f1
Create Date: 2025-03-23 11:44:03.187775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision: str = '56a9446527bb'
down_revision: Union[str, None] = '6829279ab8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('length_meters', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('width_meters', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('draft_meters', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_speed_knots', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vessel_type_id', sa.Integer(), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('production_year', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('imo_number', sa.String(length=20), nullable=True),
    sa.Column('mmsi_number', sa.String(length=20), nullable=True),
    sa.Column('call_sigh', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('active', 'maintenance', 'retired', 'out_of_service', name='equipment_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_type_id'], ['vessel_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sigh'),
    sa.UniqueConstraint('imo_number'),
    sa.UniqueConstraint('mmsi_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.drop_constraint('fleets_operator_id_fkey', 'fleets', type_='foreignkey')
    op.create_foreign_key(None, 'fleets', 'operators', ['operator_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fleets', type_='foreignkey')
    op.create_foreign_key('fleets_operator_id_fkey', 'fleets', 'operators', ['operator_id'], ['id'])
    op.drop_table('vessels')
    op.drop_table('vessel_types')
    # ### end Alembic commands ###
