"""sensor_readings

Revision ID: 89fe79911c77
Revises: 9d0ca2fdb74e
Create Date: 2025-03-25 14:11:31.554941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision: str = '89fe79911c77'
down_revision: Union[str, None] = '9d0ca2fdb74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_readings_sensor_timestamp', 'sensor_readings', ['sensor_id', 'timestamp'], unique=False)
    op.create_index('idx_sensor_readings_timestamp', 'sensor_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sensor_readings_timestamp', table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_sensor_timestamp', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
