"""sensors relations

Revision ID: 9d0ca2fdb74e
Revises: 629efc2a60ad
Create Date: 2025-03-25 13:30:18.882645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


# revision identifiers, used by Alembic.
revision: str = '9d0ca2fdb74e'
down_revision: Union[str, None] = '629efc2a60ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_types', sa.Column('min_val', sa.Numeric(), nullable=True))
    op.add_column('sensor_types', sa.Column('max_val', sa.Numeric(), nullable=True))
    op.drop_column('sensor_types', 'normal_max_val')
    op.drop_column('sensor_types', 'normal_min_val')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_types', sa.Column('normal_min_val', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('sensor_types', sa.Column('normal_max_val', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('sensor_types', 'max_val')
    op.drop_column('sensor_types', 'min_val')
    # ### end Alembic commands ###
