"""relations

Revision ID: cb202bfa50fe
Revises: 56a9446527bb
Create Date: 2025-03-23 12:28:08.204204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb202bfa50fe'
down_revision: Union[str, None] = '56a9446527bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('call_sign', sa.String(length=20), nullable=True))
    op.alter_column('vessels', 'vessel_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vessels', 'operator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vessels', 'status',
               existing_type=postgresql.ENUM('active', 'maintenance', 'retired', 'out_of_service', name='equipment_status_enum'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint('vessels_call_sigh_key', 'vessels', type_='unique')
    op.create_unique_constraint(None, 'vessels', ['call_sign'])
    op.drop_constraint('vessels_manufacturer_id_fkey', 'vessels', type_='foreignkey')
    op.drop_column('vessels', 'manufacturer_id')
    op.drop_column('vessels', 'call_sigh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('call_sigh', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vessels', sa.Column('manufacturer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vessels_manufacturer_id_fkey', 'vessels', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'vessels', type_='unique')
    op.create_unique_constraint('vessels_call_sigh_key', 'vessels', ['call_sigh'])
    op.alter_column('vessels', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('active', 'maintenance', 'retired', 'out_of_service', name='equipment_status_enum'),
               existing_nullable=True)
    op.alter_column('vessels', 'operator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vessels', 'vessel_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vessels', 'call_sign')
    # ### end Alembic commands ###
